//! Protocol events for UDP communication.
//!
//! This module contains the event types emitted by the UDP protocol layer.

use crate::frame_info::PlayerInput;
use crate::{Config, PlayerHandle};

/// Events generated by the UDP protocol layer.
///
/// These events are emitted during protocol operation to notify the session layer
/// of state changes and received data.
///
/// # Note
///
/// This type is re-exported in [`__internal`](crate::__internal) for testing and fuzzing.
/// It is not part of the stable public API.
#[derive(Debug, Clone, PartialEq)]
pub enum Event<T>
where
    T: Config,
{
    /// The session is currently synchronizing with the remote client. It will continue until `count` reaches `total`.
    Synchronizing {
        /// Total sync roundtrips required.
        total: u32,
        /// Completed sync roundtrips so far.
        count: u32,
        /// Total sync requests sent (includes retries due to packet loss).
        total_requests_sent: u32,
        /// Milliseconds elapsed since sync started.
        elapsed_ms: u128,
    },
    /// The session is now synchronized with the remote client.
    Synchronized,
    /// The session has received an input from the remote client. This event will not be forwarded to the user.
    Input {
        input: PlayerInput<T::Input>,
        player: PlayerHandle,
    },
    /// The remote client has disconnected.
    Disconnected,
    /// The session has not received packets from the remote client since `disconnect_timeout` ms.
    NetworkInterrupted { disconnect_timeout: u128 },
    /// Sent only after a `NetworkInterrupted` event, if communication has resumed.
    NetworkResumed,
    /// Synchronization has timed out. This is only emitted if a sync timeout was configured.
    /// The session will continue trying to sync, but the user may choose to abort.
    SyncTimeout {
        /// Milliseconds elapsed since sync started.
        elapsed_ms: u128,
    },
}
