name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure session with...
        2. Call method...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using?
      options:
        - stable (latest)
        - stable (older)
        - beta
        - nightly
    validations:
      required: true

  - type: input
    id: fortress-version
    attributes:
      label: Fortress Rollback Version
      description: What version of Fortress Rollback are you using?
      placeholder: e.g., 0.4.0 or git commit hash
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.).
      placeholder: Any additional information...
    validations:
      required: false
