#!/usr/bin/env python3
"""Regression tests for the automated release preparation workflow."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest
from scripts.release import prepare_release

REPO_ROOT = Path(__file__).resolve().parents[2]
PREPARE_SCRIPT = REPO_ROOT / "scripts" / "release" / "prepare_release.py"


def _write_fixture(tmp_path: Path, *, notes: str = "### Added\n\n- A feature.\n") -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "Cargo.toml").write_text(
        '[workspace]\nmembers = ["."]\n\n'
        '[package]\nname = "fortress-rollback"\nversion = "1.2.3"\n',
        encoding="utf-8",
    )
    (repo / "Cargo.lock").write_text(
        """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fortress-rollback"
version = "1.2.3"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.0"
""",
        encoding="utf-8",
    )
    (repo / "CHANGELOG.md").write_text(
        """# Changelog

## [Unreleased]

"""
        + notes
        + """
## [1.2.3] - 2026-01-01

- Previous release.

[Unreleased]: https://github.com/wallstop/fortress-rollback/compare/v1.2.3...HEAD
[1.2.3]: https://github.com/wallstop/fortress-rollback/releases/tag/v1.2.3
""",
        encoding="utf-8",
    )
    subprocess.run(["git", "init", "--quiet"], cwd=repo, check=True)
    subprocess.run(["git", "add", "--all"], cwd=repo, check=True)
    return repo


def _track(repo: Path, *paths: Path) -> None:
    subprocess.run(
        ["git", "add", "--", *(str(path.relative_to(repo)) for path in paths)],
        cwd=repo,
        check=True,
    )


def _tracked_bytes(repo: Path) -> dict[str, bytes]:
    result = subprocess.run(
        ["git", "ls-files", "-z"], cwd=repo, capture_output=True, check=True
    )
    names = result.stdout.decode("utf-8").rstrip("\0").split("\0")
    return {name: (repo / name).read_bytes() for name in names if name}


def _write_standalone(repo: Path, relative: str, lock: str, *, track: bool = True) -> Path:
    fixture_dir = repo / relative
    fixture_dir.mkdir(parents=True)
    manifest = fixture_dir / "Cargo.toml"
    manifest.write_text("[workspace]\n", encoding="utf-8")
    lockfile = fixture_dir / "Cargo.lock"
    lockfile.write_text(lock, encoding="utf-8")
    if track:
        _track(repo, manifest, lockfile)
    return lockfile


def _run(repo: Path, bump: str, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            "python3",
            str(PREPARE_SCRIPT),
            "--repo-root",
            str(repo),
            "--bump",
            bump,
            "--date",
            "2026-07-12",
            *extra,
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


def _list_manifests(repo: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            "python3",
            str(PREPARE_SCRIPT),
            "--repo-root",
            str(repo),
            "--print-standalone-manifests",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.mark.parametrize(
    ("bump", "expected"),
    [("patch", "1.2.4"), ("minor", "1.3.0"), ("major", "2.0.0")],
)
def test_prepare_release_bumps_manifest_lock_and_changelog(
    tmp_path: Path, bump: str, expected: str
) -> None:
    repo = _write_fixture(tmp_path)

    result = _run(repo, bump)

    assert result.returncode == 0, result.stdout + result.stderr
    assert f'version = "{expected}"' in (repo / "Cargo.toml").read_text()
    lock = (repo / "Cargo.lock").read_text()
    assert f'name = "fortress-rollback"\nversion = "{expected}"' in lock
    assert 'name = "serde"\nversion = "1.0.0"' in lock
    changelog = (repo / "CHANGELOG.md").read_text()
    assert f"## [{expected}] - 2026-07-12\n\n### Added" in changelog
    assert f"[{expected}]: https://github.com/wallstop/fortress-rollback/compare/v1.2.3...v{expected}" in changelog
    assert f"prepared_version={expected}" in result.stdout


def test_prepare_release_dry_run_does_not_write(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    before = _tracked_bytes(repo)

    result = _run(repo, "patch", "--dry-run")

    assert result.returncode == 0, result.stdout + result.stderr
    assert _tracked_bytes(repo) == before
    assert "--- Cargo.toml" in result.stdout
    assert "prepared_version=1.2.4" in result.stdout


def test_prepare_release_nested_dry_run_shows_complete_diff_without_writes(
    tmp_path: Path,
) -> None:
    repo = _write_fixture(tmp_path)
    nested = _write_standalone(
        repo,
        "tests/standalone",
        'version = 4\n\n[[package]]\nname = "fortress-rollback"\nversion = "0.8.0"\n',
    )
    before = _tracked_bytes(repo)

    result = _run(repo, "patch", "--dry-run")

    assert result.returncode == 0, result.stdout + result.stderr
    assert _tracked_bytes(repo) == before
    assert "--- tests/standalone/Cargo.lock" in result.stdout
    assert '-version = "0.8.0"' in result.stdout
    assert '+version = "1.2.4"' in result.stdout
    assert nested.read_bytes() == before["tests/standalone/Cargo.lock"]


def test_prepare_release_updates_standalone_path_dependency_lockfiles(
    tmp_path: Path,
) -> None:
    repo = _write_fixture(tmp_path)
    fixture_dir = repo / "tests" / "standalone"
    fixture_dir.mkdir(parents=True)
    (fixture_dir / "Cargo.toml").write_text("[workspace]\n", encoding="utf-8")
    fixture_lock = fixture_dir / "Cargo.lock"
    fixture_lock.write_text(
        """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fortress-rollback"
version = "0.1.2"
dependencies = [
 "serde",
]

[[package]]
name = "fortress-rollback"
version = "9.9.9"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "serde"
version = "1.0.0"
""",
        encoding="utf-8",
    )
    _track(repo, fixture_dir / "Cargo.toml", fixture_lock)

    result = _run(repo, "minor")

    assert result.returncode == 0, result.stdout + result.stderr
    lock = fixture_lock.read_text(encoding="utf-8")
    assert 'name = "fortress-rollback"\nversion = "1.3.0"' in lock
    assert 'name = "fortress-rollback"\nversion = "9.9.9"\nsource = "registry+' in lock
    assert 'name = "serde"\nversion = "1.0.0"' in lock


@pytest.mark.parametrize(
    ("lock", "expected"),
    [
        ("not = valid = toml", "invalid Cargo.lock"),
        (
            'version = 4\n\n[[package]]\nname = "fortress-rollback"\nversion = "0.1.0"\n'
            '\n[[package]]\nname = "fortress-rollback"\nversion = "0.2.0"\n',
            "at most one local fortress-rollback package",
        ),
    ],
)
def test_prepare_release_rejects_invalid_nested_lock_before_any_write(
    tmp_path: Path, lock: str, expected: str
) -> None:
    repo = _write_fixture(tmp_path)
    _write_standalone(repo, "nested", lock)
    before = _tracked_bytes(repo)

    result = _run(repo, "patch")

    assert result.returncode == 1
    assert expected in result.stderr
    assert _tracked_bytes(repo) == before


def test_prepare_release_rolls_back_all_replacements_after_late_failure(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _write_fixture(tmp_path)
    before = _tracked_bytes(repo)
    _, prepared = prepare_release.prepare(repo, "patch", "2026-07-12")
    real_replace = prepare_release.os.replace
    failed = False

    def fail_last_replacement(source: Path, destination: Path) -> None:
        nonlocal failed
        if not failed and ".new." in Path(source).name and Path(destination).name == "CHANGELOG.md":
            failed = True
            raise OSError("injected late replacement failure")
        real_replace(source, destination)

    monkeypatch.setattr(prepare_release.os, "replace", fail_last_replacement)

    with pytest.raises(prepare_release.PreparationError, match="injected late"):
        prepare_release.write_prepared_files(prepared)

    assert failed
    assert _tracked_bytes(repo) == before
    assert not [
        path
        for path in repo.iterdir()
        if ".new." in path.name or ".rollback." in path.name
    ]


def test_prepare_release_leaves_unrelated_standalone_lock_unchanged(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    unrelated = _write_standalone(
        repo,
        "tools/unrelated",
        'version = 4\n\n[[package]]\nname = "unrelated"\nversion = "9.8.7"\n',
    )
    before = unrelated.read_bytes()

    result = _run(repo, "patch")

    assert result.returncode == 0, result.stdout + result.stderr
    assert unrelated.read_bytes() == before


def test_manifest_discovery_excludes_untracked_and_root_workspace_member_locks(
    tmp_path: Path,
) -> None:
    repo = _write_fixture(tmp_path)
    root_manifest = repo / "Cargo.toml"
    root_manifest.write_text(
        root_manifest.read_text().replace('members = ["."]', 'members = [".", "member"]')
    )
    member = repo / "member"
    member.mkdir()
    member_manifest = member / "Cargo.toml"
    member_manifest.write_text('[package]\nname = "member"\nversion = "0.1.0"\n')
    member_lock = member / "Cargo.lock"
    member_lock.write_text(
        'version = 4\n\n[[package]]\nname = "fortress-rollback"\nversion = "0.1.0"\n'
    )
    _track(repo, root_manifest, member_manifest, member_lock)
    _write_standalone(
        repo,
        "target/generated",
        'version = 4\n\n[[package]]\nname = "fortress-rollback"\nversion = "0.1.0"\n',
        track=False,
    )

    result = _list_manifests(repo)

    assert result.returncode == 0, result.stdout + result.stderr
    assert result.stdout == ""


def test_actual_repository_standalone_manifest_set_is_authoritative() -> None:
    result = _list_manifests(REPO_ROOT)

    assert result.returncode == 0, result.stdout + result.stderr
    assert result.stdout.splitlines() == [
        "fuzz/Cargo.toml",
        "loom-tests/Cargo.toml",
        "tests/godot-emscripten/Cargo.toml",
    ]


def test_prepare_release_rejects_empty_unreleased_notes(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path, notes="")

    result = _run(repo, "patch")

    assert result.returncode != 0
    assert "Unreleased section has no release notes" in result.stderr
    assert 'version = "1.2.3"' in (repo / "Cargo.toml").read_text()


def test_prepare_release_rejects_lockfile_version_mismatch(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    lock_path = repo / "Cargo.lock"
    lock_path.write_text(
        lock_path.read_text().replace(
            'name = "fortress-rollback"\nversion = "1.2.3"',
            'name = "fortress-rollback"\nversion = "1.2.2"',
        )
    )

    result = _run(repo, "minor")

    assert result.returncode != 0
    assert "Cargo.lock package version 1.2.2 does not match Cargo.toml 1.2.3" in result.stderr
    assert 'version = "1.2.3"' in (repo / "Cargo.toml").read_text()


def test_prepare_release_rejects_existing_target_section(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    changelog_path = repo / "CHANGELOG.md"
    changelog_path.write_text(
        changelog_path.read_text().replace(
            "## [1.2.3] - 2026-01-01", "## [1.2.4] - 2026-01-01"
        )
    )

    result = _run(repo, "patch")

    assert result.returncode != 0
    assert "already contains a 1.2.4 release heading" in result.stderr
