#!/usr/bin/env python3
"""Regression tests for the automated release preparation workflow."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
PREPARE_SCRIPT = REPO_ROOT / "scripts" / "release" / "prepare_release.py"


def _write_fixture(tmp_path: Path, *, notes: str = "### Added\n\n- A feature.\n") -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "Cargo.toml").write_text(
        '[package]\nname = "fortress-rollback"\nversion = "1.2.3"\n',
        encoding="utf-8",
    )
    (repo / "Cargo.lock").write_text(
        """# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "fortress-rollback"
version = "1.2.3"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.0"
""",
        encoding="utf-8",
    )
    (repo / "CHANGELOG.md").write_text(
        """# Changelog

## [Unreleased]

"""
        + notes
        + """
## [1.2.3] - 2026-01-01

- Previous release.

[Unreleased]: https://github.com/wallstop/fortress-rollback/compare/v1.2.3...HEAD
[1.2.3]: https://github.com/wallstop/fortress-rollback/releases/tag/v1.2.3
""",
        encoding="utf-8",
    )
    return repo


def _run(repo: Path, bump: str, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            "python3",
            str(PREPARE_SCRIPT),
            "--repo-root",
            str(repo),
            "--bump",
            bump,
            "--date",
            "2026-07-12",
            *extra,
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.mark.parametrize(
    ("bump", "expected"),
    [("patch", "1.2.4"), ("minor", "1.3.0"), ("major", "2.0.0")],
)
def test_prepare_release_bumps_manifest_lock_and_changelog(
    tmp_path: Path, bump: str, expected: str
) -> None:
    repo = _write_fixture(tmp_path)

    result = _run(repo, bump)

    assert result.returncode == 0, result.stdout + result.stderr
    assert f'version = "{expected}"' in (repo / "Cargo.toml").read_text()
    lock = (repo / "Cargo.lock").read_text()
    assert f'name = "fortress-rollback"\nversion = "{expected}"' in lock
    assert 'name = "serde"\nversion = "1.0.0"' in lock
    changelog = (repo / "CHANGELOG.md").read_text()
    assert f"## [{expected}] - 2026-07-12\n\n### Added" in changelog
    assert f"[{expected}]: https://github.com/wallstop/fortress-rollback/compare/v1.2.3...v{expected}" in changelog
    assert f"prepared_version={expected}" in result.stdout


def test_prepare_release_dry_run_does_not_write(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    before = {path.name: path.read_bytes() for path in repo.iterdir()}

    result = _run(repo, "patch", "--dry-run")

    assert result.returncode == 0, result.stdout + result.stderr
    assert {path.name: path.read_bytes() for path in repo.iterdir()} == before
    assert "--- Cargo.toml" in result.stdout
    assert "prepared_version=1.2.4" in result.stdout


def test_prepare_release_rejects_empty_unreleased_notes(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path, notes="")

    result = _run(repo, "patch")

    assert result.returncode != 0
    assert "Unreleased section has no release notes" in result.stderr
    assert 'version = "1.2.3"' in (repo / "Cargo.toml").read_text()


def test_prepare_release_rejects_lockfile_version_mismatch(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    lock_path = repo / "Cargo.lock"
    lock_path.write_text(
        lock_path.read_text().replace(
            'name = "fortress-rollback"\nversion = "1.2.3"',
            'name = "fortress-rollback"\nversion = "1.2.2"',
        )
    )

    result = _run(repo, "minor")

    assert result.returncode != 0
    assert "Cargo.lock package version 1.2.2 does not match Cargo.toml 1.2.3" in result.stderr
    assert 'version = "1.2.3"' in (repo / "Cargo.toml").read_text()


def test_prepare_release_rejects_existing_target_section(tmp_path: Path) -> None:
    repo = _write_fixture(tmp_path)
    changelog_path = repo / "CHANGELOG.md"
    changelog_path.write_text(
        changelog_path.read_text().replace(
            "## [1.2.3] - 2026-01-01", "## [1.2.4] - 2026-01-01"
        )
    )

    result = _run(repo, "patch")

    assert result.returncode != 0
    assert "already contains a 1.2.4 release heading" in result.stderr
