#!/bin/bash
# Welcome script for Fortress Rollback devcontainer

# Only run once per terminal session
if [ -n "$FORTRESS_WELCOME_SHOWN" ]; then
    return 2>/dev/null || exit 0
fi
export FORTRESS_WELCOME_SHOWN=1

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║     Fortress Rollback - Full Verification Environment           ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Available verification tools:"
echo ""
echo "  TLA+ Model Checker:"
echo "    tlc <spec.tla>                    # Run TLC model checker"
echo "    sany <spec.tla>                   # Parse/check TLA+ spec"
echo "    ./scripts/verify-tla.sh           # Verify all TLA+ specs"
echo ""
echo "  Kani (Bounded Model Checker for Rust):"
echo "    cargo kani                        # Run all Kani proofs"
echo "    cargo kani --harness <name>       # Run specific proof"
echo "    ./scripts/verify-kani.sh          # Verify with helper script"
echo "    ./scripts/check-kani-coverage.sh  # Validate proof coverage"
echo ""
echo "  Miri (Undefined Behavior Detection):"
echo "    cargo +nightly miri test          # Run tests under Miri"
echo "    cargo +nightly miri run           # Run binary under Miri"
echo ""
echo "  Concurrency Testing:"
echo "    # Use loom in tests (already in dev-dependencies)"
echo ""
echo "  Z3 Theorem Prover:"
echo "    cargo test --test test_z3_verification  # Run Z3 proofs"
echo "    python3 -c 'import z3; print(z3.get_version_string())'"
echo ""
echo "  Testing & Coverage:"
echo "    cargo test                        # Run all tests"
echo "    cargo nextest run                 # Faster parallel testing"
echo "    cargo tarpaulin                   # Code coverage report"
echo "    cargo llvm-cov                    # LLVM-based coverage"
echo "    cargo mutants                     # Mutation testing"
echo ""
echo "  Auditing & Quality:"
echo "    cargo audit                       # Security vulnerability check"
echo "    cargo deny check                  # License/dependency check"
echo "    cargo clippy --all-targets        # Linting"
echo "    cargo shear                       # Unused dependency detection"
echo "    cargo spellcheck                  # Documentation spelling"
echo "    cargo geiger                      # Unsafe code audit"
echo "    cargo +nightly careful test       # Extra runtime safety checks"
echo ""
echo "  CI/CD Linting:"
echo "    markdownlint '**/*.md'            # Markdown linting"
echo "    markdown-link-check <file.md>    # Check markdown links"
echo "    vale docs/                        # Prose linting (docs/)"
echo "    actionlint                        # GitHub Actions linting"
echo "    yamllint <file.yml>               # YAML linting"
echo ""
echo "  Profiling:"
echo "    cargo flamegraph                  # Generate flame graphs"
echo ""
echo "  All-in-one verification:"
echo "    ./scripts/verify-all.sh           # Run all verifiers"
echo ""
echo "  High-Performance CLI Tools (aliased, use instead of standard):"
echo "    rg (ripgrep)  → grep              fd → find"
echo "    bat           → cat               eza → ls"
echo "    sd            → sed               delta → diff"
echo "    dust          → du                duf → df"
echo "    procs         → ps                htop/btm → top"
echo "    hyperfine     → time              tokei → wc -l"
echo "    z (zoxide)    → cd (smart jump)"
echo ""
echo "  NOTE: When calling 'bat' directly, always use --paging=never"
echo "        to prevent blocking. The 'cat' alias does this automatically."
echo ""
echo "───────────────────────────────────────────────────────────────────"
