#!/bin/bash
# Install Git Hooks for Fortress Rollback
#
# This script installs the pre-commit framework hooks for the
# Fortress Rollback project.
#
# Usage:
#   ./scripts/install-hooks.sh
#   ./scripts/install-hooks.sh --uninstall

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Get the project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

# Parse arguments
UNINSTALL=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --uninstall)
            UNINSTALL=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --uninstall  Remove installed hooks"
            echo "  --help       Show this help message"
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Check if we're in a git repository
if [[ ! -d "$PROJECT_ROOT/.git" ]]; then
    echo -e "${RED}Error: Not a git repository${NC}"
    exit 1
fi

mkdir -p "$HOOKS_DIR"

if [[ "$UNINSTALL" == "true" ]]; then
    echo -e "${BLUE}Uninstalling git hooks...${NC}"

    if command -v pre-commit > /dev/null 2>&1; then
        pre-commit uninstall --hook-type pre-commit || true
        pre-commit uninstall --hook-type pre-push || true
    fi

    # Remove only hooks managed by this project; preserve custom hooks.
    for hook in pre-commit pre-push; do
        hook_path="$HOOKS_DIR/$hook"
        if [[ ! -f "$hook_path" ]]; then
            echo -e "${YELLOW}•${NC} $hook hook not installed"
        elif grep -qE "File generated by pre-commit|Pre-commit hook for Fortress Rollback" "$hook_path"; then
            rm "$hook_path"
            echo -e "${GREEN}✓${NC} Removed $hook hook"
        else
            echo -e "${YELLOW}•${NC} Preserved custom $hook hook"
        fi
    done

    echo -e "${GREEN}Done!${NC}"
    exit 0
fi

echo -e "${BLUE}Installing git hooks for Fortress Rollback...${NC}"
echo ""

if ! command -v pre-commit > /dev/null 2>&1; then
    echo -e "${RED}✗${NC} pre-commit is not installed"
    echo -e "${YELLOW}Install it with:${NC} pip install pre-commit"
    exit 1
fi

# Remove this repository's legacy standalone hook before installing the
# framework hook. Truly custom hooks are left in place for pre-commit's
# migration mode to preserve and run.
for hook in pre-commit pre-push; do
    hook_path="$HOOKS_DIR/$hook"
    if [[ -f "$hook_path" ]] && grep -q "Pre-commit hook for Fortress Rollback" "$hook_path"; then
        rm "$hook_path"
        echo -e "${GREEN}✓${NC} Removed legacy Fortress Rollback $hook hook"
    fi
done

# Do not use --overwrite here: pre-commit's migration mode preserves truly
# custom hooks and runs them after the generated framework hook.
pre-commit install --hook-type pre-commit --hook-type pre-push
echo -e "${GREEN}✓${NC} Installed pre-commit framework hooks"

# Make sync-version.sh executable
SYNC_SCRIPT="$SCRIPT_DIR/sync-version.sh"
if [[ -f "$SYNC_SCRIPT" ]]; then
    chmod +x "$SYNC_SCRIPT"
    echo -e "${GREEN}✓${NC} Made sync-version.sh executable"
fi

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Git hooks installed successfully!             ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}The following hooks are now active:${NC}"
echo -e "  ${GREEN}•${NC} pre-commit - Fast staged/file-scoped checks"
echo -e "  ${GREEN}•${NC} pre-push - Lightweight push checks"
echo ""
echo -e "${BLUE}To uninstall:${NC} $0 --uninstall"
