#!/usr/bin/env python3
"""Regenerate .llm/skills/_index.md from skill file metadata.

Scans all .md files in .llm/skills/ (excluding _index.md) for metadata
comments (<!-- WHEN: ... --> and <!-- CATEGORY: ... -->), then generates
a categorized index.

Modes:
  (default)   Overwrite _index.md if stale; exit 1 so pre-commit shows
              the auto-fix, exit 0 if already up-to-date.
  --check     Read-only: exit 1 if the index would change, exit 0 if
              up-to-date. Used in CI to verify the index is current.

Cross-platform: Works on Linux, macOS, and Windows.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

INDEX_FILENAME = "_index.md"
DEFAULT_CATEGORY = "Uncategorized"

WHEN_RE = re.compile(r"<!--\s*WHEN:\s*(.+?)\s*-->")
CATEGORY_RE = re.compile(r"<!--\s*CATEGORY:\s*(.+?)\s*-->")


def extract_metadata(
    filepath: Path, repo_root: Path | None = None
) -> tuple[str, str] | None:
    """Extract WHEN trigger and CATEGORY from a skill file.

    Returns (category, when_trigger), or None on read error.
    Falls back to DEFAULT_CATEGORY and the first heading line (or
    filename) when metadata comments are absent.
    """
    if repo_root is not None:
        try:
            display_path = filepath.relative_to(repo_root)
        except ValueError:
            display_path = filepath
    else:
        display_path = filepath

    try:
        content = filepath.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        print(f"{display_path}:0: cannot read file: {exc}", file=sys.stderr)
        return None

    category = DEFAULT_CATEGORY
    when = ""

    cat_match = CATEGORY_RE.search(content)
    if cat_match:
        category = cat_match.group(1).strip()

    when_match = WHEN_RE.search(content)
    if when_match:
        when = when_match.group(1).strip()

    # Fallback: use the first markdown heading as the trigger description
    if not when:
        for line in content.splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                when = stripped.lstrip("# ").strip()
                break

    if not when:
        when = filepath.stem.replace("-", " ")

    return category, when


def build_index(
    skills_dir: Path, repo_root: Path | None = None
) -> tuple[str, bool]:
    """Build the index content from skill files.

    Returns (index_content, had_error).  had_error is True if any skill
    file could not be read.
    """
    skill_files = sorted(
        f
        for f in skills_dir.glob("*.md")
        if f.name != INDEX_FILENAME
    )

    # Collect entries grouped by category
    had_error = False
    categories: dict[str, list[tuple[str, str]]] = {}
    for filepath in skill_files:
        result = extract_metadata(filepath, repo_root)
        if result is None:
            had_error = True
            continue
        category, when = result
        categories.setdefault(category, []).append((filepath.name, when))

    # Sort categories alphabetically, but put Uncategorized last
    sorted_cats = sorted(
        categories.keys(),
        key=lambda c: (c == DEFAULT_CATEGORY, c),
    )

    lines: list[str] = [
        "# Skills Index",
        "",
        "<!-- Auto-generated by scripts/hooks/regenerate-skills-index.py"
        " — do not edit manually -->",
    ]

    for cat in sorted_cats:
        lines.append("")
        lines.append(f"## {cat}")
        lines.append("")
        lines.append("| Skill | When to Use |")
        lines.append("|-------|-------------|")
        for filename, when in sorted(categories[cat]):
            lines.append(f"| [{filename}]({filename}) | {when} |")

    # Ensure trailing newline
    lines.append("")
    return "\n".join(lines), had_error


def main() -> int:
    check_only = "--check" in sys.argv

    repo_root = Path(__file__).resolve().parent.parent.parent
    skills_dir = repo_root / ".llm" / "skills"
    index_path = skills_dir / INDEX_FILENAME

    if not skills_dir.is_dir():
        # Nothing to index
        return 0

    new_content, had_error = build_index(skills_dir, repo_root)

    if had_error:
        print("Aborting: one or more skill files could not be read.", file=sys.stderr)
        return 1

    # Compare with existing index
    try:
        rel_index = index_path.relative_to(repo_root)
    except ValueError:
        rel_index = index_path
    existing = ""
    if index_path.is_file():
        try:
            existing = index_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            print(f"{rel_index}:0: cannot read file: {exc}", file=sys.stderr)
            return 1

    if new_content == existing:
        return 0  # Already up-to-date

    if check_only:
        print(
            f"Skills index is out-of-date: {rel_index}",
            file=sys.stderr,
        )
        print("Run 'python scripts/hooks/regenerate-skills-index.py' to fix.", file=sys.stderr)
        return 1

    # Write updated index
    try:
        index_path.write_text(new_content, encoding="utf-8")
    except OSError as e:
        print(f"{rel_index}:0: cannot write file: {e}", file=sys.stderr)
        return 1

    print(f"Updated {rel_index}")
    return 1  # Exit 1 so pre-commit shows the auto-fix


if __name__ == "__main__":
    sys.exit(main())
